---
name: cs580s2020_peer-reviews
break: true
fastfail: false
indent: 4
---
IntroOutline.md:
        CountFileWords --count 200
        ConfirmFileExists
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "Add Name Here" --count 0 --exact
        MatchFileFragment --fragment "Add Name Here" --count 0 --exact
    	CountMarkdownTags --tag "list" --count 1 --exact
    	CountMarkdownTags --tag "heading" --count 6 --exact
CountCommits --count 1
